name: Build Container

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: "startsWith(github.ref, 'refs/tags/v')"
        name: build container (release)
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/deltalaboratory/signing-server:latest
            ghcr.io/deltalaboratory/signing-server:${{ github.ref_name }}
            ghcr.io/deltalaboratory/signing-server:${{ github.sha }}
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        name: build container (development)
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/deltalaboratory/signing-server:development
            ghcr.io/deltalaboratory/signing-server:${{ github.sha }}